#!/usr/bin/env bash


ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
#ssh user@machine.com "pkill java; pkill screen"
#ssh user@machine.com "pkill java; pkill screen"
#ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
ssh user@machine.com "pkill java; pkill screen"
#ssh user@machine.com "pkill java; pkill screen"
